#!/bin/bash

fits_file_source_dir="./S82Coadds" # This is the directory containing the original coadds by Fliri & Trujillo
work_dir = "/var/tmp"
tile_directory="./tiles"

# generate or modify swarp.default in advance
swarp -d # generates the one-piece fits file of stripe 82

mSubimage -d "$work_dir/coadd.fits" "$work_dir/cut.fits" 5 0 110 2.5 # the large fits generated by swarp has borders, cut down to the S82 official size

#mConvert -b -32 cut.fits cut.fits # the output of mSubimage is 64 bit floats, we want 32 bit floats

# generate the tiles
ycount=0
xcount=0
x_pix=554902 # pixels of the large fits file in x direction
y_pix=22729 # pixels of the large fits file in y direction
for ((y=1;y<y_pix; y+=128)) ; do 
    for ((x=1;x<x_pix; x+=128)) ; do 
	# echo $xcount-$ycount $x $y #Debug output
	mSubimage -p "$work_dir/cut.fits" "$tile_directory/$xcount-$ycount.fits" $x $y 127 
	mConvert -b -32 "$tile_directory/$xcount-$ycount.fits"  "$tile_directory/$xcount-$ycount.fits"
	xcount=$((xcount+1)) 
    done 
    ycount=$((ycount+1))
    xcount=0
done
echo "$ycount tiles in y direction"

#TODO reverse y-coordinate naming 1 <-> max_y, 2 <-> max_y -1, ...